### ISSUE TITLE
NUM_CHUNKS miscalculation

### ISSUE THREAD

**Issue by jasongilman** [prestonlimlianjie/aws-s3-multipart-presigned-upload#1]
I noticed an issue with calculating the number of chunks that could cause a problem

```
const NUM_CHUNKS = Math.round(fileSize / FILE_CHUNK_SIZE) + 1
```

If the `fileSize/FILE_CHUNK_SIZE` remainder is >= 5 then `Math.round` will round up and the number of chunks will be 1 more than needed. `Math.floor` would solve this issue.

This is a really great example library. Thanks for posting this!

**Comment by prestonlimlianjie** [comment]
Thanks for pointing out the bug @jasongilman! And I'm glad you found this helpful!
