### ISSUE TITLE
Error: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

### ISSUE THREAD

**Issue by AhchimLee** [prestonlimlianjie/aws-s3-multipart-presigned-upload#8]
I tried to upload a file to S3, but it failed with the corresponding error.
I also tried it on a public bucket because it might be a permission issue, but even this failed.
Why is the XML Malformed?
I tried to debug, but there is no output to the console from the frontend.
I don't know much about Node or JS, and need help.

**Comment by AhchimLee** [comment]
It was due to a missing CORS configuration on the S3 bucket.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>etag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
  </CORSRule>
</CORSConfiguration>
```

Make sure to have `etag` as an exposed header.

**Comment by kimcrab** [comment]
> It was due to a missing CORS configuration on the S3 bucket.
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
>   <CORSRule>
>     <AllowedOrigin>*</AllowedOrigin>
>     <AllowedMethod>PUT</AllowedMethod>
>     <AllowedMethod>POST</AllowedMethod>
>     <AllowedMethod>GET</AllowedMethod>
>     <MaxAgeSeconds>3000</MaxAgeSeconds>
>     <ExposeHeader>etag</ExposeHeader>
>     <AllowedHeader>*</AllowedHeader>
>   </CORSRule>
> </CORSConfiguration>
> ```
> 
> Make sure to have `etag` as an exposed header.

You literally saved my day!
